packages:
  - playground
  - playground-nuxt

ignoredBuiltDependencies:
  - esbuild
  - protobufjs
  - unrs-resolver

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@rocicorp/zero-sqlite3'
  - oxc-resolver
  - simple-git-hooks
